sscl/urls.py
from django.conf.urls import url
from django.contrib import admin

from people import views as people_views
from sscl import views

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^clear/', views.clear, {}, 'clear'),
    url(r'^clear-texts/', views.clear_texts, {}, 'clear-texts'),
    url(r'^history/', views.history, {}, 'history'),
    url(r'^announcement/', views.announcement, {}, 'announcement'),
    url(r'^callback/', views.callback, {}, 'callback'),
    url(r'^thank-you/', people_views.thank_you, {}, 'thank-you'),
    url(r'^msg', people_views.msg, {}, 'confirm'),
    url(r'^confirm/(?P<hash>.*)/yes', people_views.confirm_yes, {}, 'confirm-yes'),
    url(r'^confirm/(?P<hash>.*)/no', people_views.confirm_no, {}, 'confirm-no'),
    url(r'^confirm/(?P<hash>.*)/', people_views.confirm, {}, 'confirm'),
    url(r'^sending-email/', people_views.sending_email, {}, 'sending-email'),
    url(r'^sending-text/', people_views.sending_text, {}, 'sending-text'),
    url(r'^unlock/', people_views.unlock, {}, 'unlock'),
    url(r'^send/', views.send_emails, {}, 'send'),
    url(r'^api/image/', views.image_update, {}, 'image'),
    url(r'^api/waivers/', views.waiver_data, {}, 'waiver-data'),
    url(r'^api/tracker/', views.tracker_data, {}, 'tracker-data'),
    url(r'^receive/', people_views.receive_text, {}, 'receive-text'),
    url(r'^delivery/', people_views.delivery, {}, 'delivery'),
    url(r'^view-delivery/', people_views.view_deliver_log, {}, 'delivery-view'),
    url(r'^$', people_views.waiver, {}, 'waiver'),
]

people/models.py
from __future__ import unicode_literals

import json
import re

from datetime import datetime
from django.conf import settings
from django.db import models
from jsonfield import JSONField

from people.helpers import get_celery_worker_status, unique_hash


class Announcement(models.Model):
    title = models.CharField(max_length=255, default="main", unique=True)
    text = models.TextField()

    def __unicode__(self):
        return self.title


class MessageTracker(models.Model):
    date = models.DateTimeField(auto_now_add=True)
    data = JSONField(default={"viewed": [], "yes": [], "no": []})
    nexmo_ids = JSONField(default=[])
    sending_email = models.BooleanField(default=False)
    sending_text = models.BooleanField(default=False)

    class Meta:
        verbose_name = 'Message Confirmation'
        verbose_name_plural = 'Message Confirmations'

    def __unicode__(self):
        return str(self.date)

    @property
    def is_sending_email(self):
        return self.sending_email and not get_celery_worker_status().get('ERROR')

    @property
    def is_sending_text(self):
        return self.sending_text and not get_celery_worker_status().get('ERROR')

    @property
    def yes_names(self):
        return sorted(self._names("yes"))

    @property
    def no_names(self):
        return sorted(self._names("no"))

    @property
    def view_names(self):
        return sorted(self._names("viewed"))

    def _names(self, field):
        data = []
        for pk in self.data[field]:
            waiver = Waiver.objects.filter(pk=pk).first()
            if waiver:
                data.append(waiver.full_name)
        return data

    @property
    def view_count(self):
        return len(self.data['viewed'])

    @property
    def yes_count(self):
        return len(self.data['yes'])

    @property
    def no_count(self):
        return len(self.data['no'])

    @property
    def has_data(self):
        return self.data['viewed'] or self.data['yes'] or self.data['no']

    @staticmethod
    def current_tracker():
        return MessageTracker.objects.latest('date')

    @staticmethod
    def viewed(waiver):
        tracker = MessageTracker.current_tracker()
        if waiver and waiver.pk not in tracker.data['viewed']:
            MessageTracker.add_to_data('viewed', waiver, tracker)

    @staticmethod
    def yes(waiver):
        tracker = MessageTracker.current_tracker()
        if waiver and waiver.pk not in tracker.data['yes']:
            MessageTracker.add_to_data('yes', waiver, tracker)

    @staticmethod
    def no(waiver):
        tracker = MessageTracker.current_tracker()
        if waiver and waiver.pk not in tracker.data['no']:
            MessageTracker.add_to_data('no', waiver, tracker)

    @staticmethod
    def add_to_data(key, waiver, tracker):
        data = tracker.data
        data_list = data[key]
        data_list.append(waiver.pk)
        data[key] = data_list
        tracker.data = data
        tracker.save()
        waiver.last_interaction = datetime.now()
        waiver.save()


class SendHistory(models.Model):
    tracker = models.ForeignKey(MessageTracker)
    email_success = JSONField(default=[])
    email_errors = JSONField(default=[])
    txt_success = JSONField(default=[])
    txt_errors = JSONField(default=[])


class Waiver(models.Model):
    CARRIERS = (
        ("@sms.3rivers.net", "3 River Wireless"),
        ("@paging.acswireless.com", "ACS Wireless"),
        ("@txt.att.net", "AT&T"),
        ("@message.alltel.com", "Alltel"),
        ("@bplmobile.com", "BPL Mobile"),
        ("@bellmobility.ca", "Bell Canada"),
        ("@txt.bellmobility.ca", "Bell Mobility"),
        ("@txt.bell.ca", "Bell Mobility (Canada)"),
        ("@blueskyfrog.com", "Blue Sky Frog"),
        ("@sms.bluecell.com", "Bluegrass Cellular"),
        ("@myboostmobile.com", "Boost Mobile"),
        ("er@cwwsms.com", "Carolina West Wireless"),
        ("@mobile.celloneusa.com", "Cellular One"),
        ("@csouth1.com", "Cellular South"),
        ("@cwemail.com", "Centennial Wireless"),
        ("@messaging.centurytel.net", "CenturyTel"),
        ("@txt.att.net", "Cingular (Now AT&T)"),
        ("@msg.clearnet.com", "Clearnet"),
        ("@comcastpcs.textmsg.com", "Comcast"),
        ("@corrwireless.net", "Corr Wireless Communications"),
        ("@sms.mycricket.com", "Cricket"),
        ("@mobile.dobson.net", "Dobson"),
        ("@sms.edgewireless.com", "Edge Wireless"),
        ("@fido.ca", "Fido"),
        ("@sms.goldentele.com", "Golden Telecom"),
        ("@msg.fi.google.com", "Google fi"),
        ("@messaging.sprintpcs.com", "Helio"),
        ("@text.houstoncellular.net", "Houston Cellular"),
        ("@ideacellular.net", "Idea Cellular"),
        ("@ivctext.com", "Illinois Valley Cellular"),
        ("@inlandlink.com", "Inland Cellular Telephone"),
        ("@pagemci.com", "MCI"),
        ("@text.mtsmobility.com", "MTS"),
        ("@mymetropcs.com", "Metro PCS"),
        ("@page.metrocall.com", "Metrocall"),
        ("@my2way.com", "Metrocall 2-way"),
        ("@fido.ca", "Microcell"),
        ("@clearlydigital.com", "Midwest Wireless"),
        ("@mobilecomm.net", "Mobilcomm"),
        ("@messaging.nextel.com", "Nextel"),
        ("@onlinebeep.net", "OnlineBeep"),
        ("@pcsone.net", "PCS One"),
        ("@txt.bell.ca", "President's Choice"),
        ("@sms.pscel.com", "Public Service Cellular"),
        ("@qwestmp.com", "Qwest"),
        ("@pcs.rogers.com", "Rogers AT&T Wireless"),
        ("@pcs.rogers.com", "Rogers Canada"),
        ("@txt.bell.ca", "Solo Mobile"),
        ("@email.swbw.com", "Southwestern Bell"),
        ("@messaging.sprintpcs.com", "Sprint"),
        ("@tms.suncom.com", "Sumcom"),
        ("@mobile.surewest.com", "Surewest Communicaitons"),
        ("@tmomail.net", "T-Mobile"),
        ("@msg.telus.com", "Telus"),
        ("@txt.att.net", "Tracfone"),
        ("@tms.suncom.com", "Triton"),
        ("@email.uscc.net", "US Cellular"),
        ("@uswestdatamail.com", "US West"),
        ("@utext.com", "Unicel"),
        ("@vtext.com", "Verizon"),
        ("@vmobl.com", "Virgin Mobile"),
        ("@vmobile.ca", "Virgin Mobile Canada"),
        ("@sms.wcc.net", "West Central Wireless"),
        ("@cellularonewest.com", "Western Wireless"),
    )

    image = models.CharField(max_length=999999, blank=True, null=True)
    created = models.DateTimeField(auto_now_add=True)
    first = models.CharField(max_length=40)
    last = models.CharField(max_length=40)
    email = models.EmailField(max_length=40)
    phone = models.CharField(max_length=16)
    carrier = models.CharField(max_length=40, choices=CARRIERS, blank=True, null=True)
    dob = models.DateField()
    signature = models.CharField(max_length=40)
    confirmed = models.BooleanField(default=False, blank=True)
    sent = models.DateTimeField(blank=True, null=True)
    hash = models.CharField(max_length=8, blank=True, null=True)
    last_interaction = models.DateTimeField(blank=True, null=True)

    def __unicode__(self):
        return self.first + " " + self.last

    def save(self, *args, **kwargs):
        if not self.hash:
            self.hash = unique_hash(Waiver, 'hash')
        self.phone = re.sub("\D", "", self.phone)
        if self.pk is None:
            self.send_new_waiver_email()
        super(Waiver, self).save(*args, **kwargs)

    @property
    def full_name(self):
        return "{} {}".format(self.first, self.last).title()

    def confirm(self):
        self.confirmed = True
        self.save()

    def cancel(self):
        self.confirmed = False
        self.save()

    @property
    def number(self):
        return self.phone + self.carrier

    def send_new_waiver_email(self):
        from people.tasks import send_with_mailgun
        to = "kazanski.zachary@gmail.com" if settings.DEBUG else "srichardson@streamsound.com"
        send_with_mailgun(to, "New Waiver: {} {}".format(self.first, self.last),
                          self.make_msg())

    def make_msg(self):
        fields = ('first', 'last', 'email', 'phone', 'carrier', 'dob')
        return "\n".join(["{}: {}".format(k, getattr(self, k))
                          for k in fields])

    def photo(self):
        if self.image:
            return '<img height="40"' \
                   'onMouseOver="this.style.height=\'175px\'"' \
                   'onMouseOut="this.style.height=\'40px\'"' \
                   'src="data:image/png;base64,{}"/>'.format(self.image)
    photo.allow_tags = True

    @property
    def _last_interaction_from_message_tracker(self):
        for m in MessageTracker.objects.order_by('-date').all():
            waiver_pks = reduce(lambda x, y: x + y, m.data.values())
            if self.pk in waiver_pks:
                return m.date


class ReceivedText(models.Model):
    waiver = models.ForeignKey(Waiver)
    text = models.CharField(max_length=255)

    @classmethod
    def create(cls, sms):
        phone = sms['msisdn'][1:] # Strip the leading +1 country code.
        waiver = Waiver.objects.filter(phone=phone).first()
        if waiver:
            instance = cls.objects.create(waiver=waiver, text=sms['text'])

people/forms.py
from django import forms

from people.models import Waiver


class Html5DateInput(forms.DateInput):
    input_type = 'date'


class WaiverForm(forms.ModelForm):
    phone = forms.RegexField(
        regex=r'\d{10,15}$',
        error_message="Only numbers are allowed. Ex: 8135558888"
    )

    def __init__(self, *args, **kwargs):
        super(WaiverForm, self).__init__(*args, **kwargs)
        for name, field in self.fields.items():
            if field.__class__ != forms.BooleanField:
                field.widget.attrs['class'] =  'form-control'
            if field.__class__ == forms.DateField:
                field.widget.attrs['type'] = 'date'
            if name == "dob":
                field.label = "Date of Birth"

    class Meta:
        model = Waiver
        exclude = ('created', 'confirmed', 'hash', 'sent', 'image', 'last_interaction', 'carrier')
        widgets = {
            'dob': Html5DateInput()
        }

templates/announcement.html
{% extends "base.html" %}

{% block title %}SSCL | Thank You{% endblock %}

{% block info %}
    {{ announcement.text|safe }}
    {% if hash %}
    <center><h2>Are you coming?</h2></center>
    <div class="row">
        <div class="col-xs-6">
            <center><a href="{% url 'confirm-yes' hash %}"><button style="width: 70%" class="btn btn-success">YES</button></a></center>
        </div>
        <div class="col-xs-6">
            <center><a href="{% url 'confirm-no' hash %}"><button style="width: 70%"class="btn btn-danger">NO</button></a></center>
        </div>
    {% endif %}
{% endblock %}

templates/base.html
<!DOCTYPE HTML>
<html>
<head>

<title>{% block title %}SSCL Basketball{% endblock %}</title>

<!-- jQuery -->
<script src="https://code.jquery.com/jquery-2.2.1.min.js"></script>
<script src="https://code.jquery.com/ui/1.11.4/jquery-ui.js"></script>

<!-- Latest compiled and minified CSS -->
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap.min.css" integrity="sha384-1q8mTJOASx8j1Au+a5WDVnPi2lkFfwwEAa8hDDdjZlpLegxhjVME1fgjWPGmkzs7" crossorigin="anonymous">
<link rel="stylesheet" href="https://code.jquery.com/ui/1.11.4/themes/smoothness/jquery-ui.css">

<!-- Latest compiled and minified JavaScript -->
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/js/bootstrap.min.js" integrity="sha384-0mSbJDEHialfmuBBQP6A4Qrprq5OVfW37PRR3j5ELqxss1yVqOtnepnHVP9aJ7xS" crossorigin="anonymous"></script>

<meta charset="utf-8">
<meta http-equiv="X-UA-Compatible" content="IE=edge">
<meta name="viewport" content="width=device-width, initial-scale=1">
</head>

<body style="background-color: rgb(119,119,119);">
<div class="container-fluid">
  <div class="row">
    <div class="hidden-xs col-md-3"></div>
    <div class="col-md-6" style="padding: 0px; background-color: white;">
      <img style="width:100%; padding:0px;" src="https://lh5.googleusercontent.com/8TEIAwUSZHXJ72chcxnollyH3ybF5bRnljAVDxzYAkY18WNMiefsLt7il3R-ZhCxM_sX" />
    </div>
    <div class="hidden-xs col-md-3"></div>
  </div>
  <div class="row">
    <div class="hidden-xs col-md-3"></div>
    <div class="col-md-6" style="background-color: white; padding-top:15px; padding-bottom:15px;">
      {% block info %}
      {% endblock %}
    </div>
    <div class="hidden-xs col-md-3"></div>
  </div>
</div>

{% block extra_scripts %}
{% endblock %}

<script>
  (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
     (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
       m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
         })(window,document,'script','https://www.google-analytics.com/analytics.js','ga');

  ga('create', 'UA-77396161-1', 'auto');
    ga('send', 'pageview');

</script>


</body>
</html>

templates/delivery.html
<html>
<body>
<ul>
{% for l in lines %}
<li>{{l}}</li>
{% endfor %}
</ul>
</body>
</html>

templates/thank_you.html
{% extends "base.html" %}

{% block title %}SSCL | Thank You{% endblock %}

{% block info %}
      <center style="margin-bottom:20px;" >
        <h1>Thank You</h1>
      </center>
{% endblock %}

templates/thank_you_no.html
{% extends "base.html" %}

{% block title %}SSCL | Thank You{% endblock %}

{% block info %}
      <center style="margin-bottom:20px;" >
        <h1>Thank You</h1>
        <h3>Hope to see you next time.</h3>
      </center>
{% endblock %}

templates/thank_you_yes.html
{% extends "base.html" %}

{% block title %}SSCL | Thank You{% endblock %}

{% block info %}
      <center style="margin-bottom:20px;" >
        <h1>Thank You</h1>
      </center>
{% endblock %}

templates/waiver.html
{% extends 'base.html' %}

{% block title %}SSCL Waiver{% endblock %}

{% block info %}
      <h4>THE MESSAGE</h4>
      <p>{{ announcement.text|safe }}</p>
      <hr>

      <h4 style="margin-top:0px;">WAIVER OF LIABILITY AND HOLD HARMLESS AGREEMENT</h4>
      <div style="font-size: 9px; color: grey;">
        <p>1. I acknowledge that I have voluntarily agreed to participate in the “Weekly Wednesday Night Basketball Activity”, (“Activity”). I hereby release, waive, discharge and covenant not to sue Cambridge Christian School or Steve Richardson, its officers, servants, agents and employees (hereinafter referred to as "Hosts") from any and all liability, claims, demands, actions and causes of action whatsoever arising out of or relating to any loss, damage or injury, including death, that may be sustained by me, or to any property belonging to me, whether caused by the negligence of the Hosts, or otherwise, while participating in the Activity, or while in, on or upon the premises where the Activity is being conducted, while in transit to or from the premises, or in any place or places connected with the Activity.</p>
        <p>2. I am fully aware of risks and hazards connected with being on the premises and participating in the Activity, and I am fully aware that there may be risks and hazards unknown to me connected with being on the premises and participating in the Activity, and I hereby elect to voluntarily participate in the Activity, to enter upon the above named premises (6101 N Habana Ave, Tampa, FL 33614) and engage in activities knowing that conditions may be hazardous, or may become hazardous or dangerous to me and my property. I voluntarily assume full responsibility for any risks of loss, property damage or personal injury, including death, that may be sustained by me, or any loss or damage to property owned by me, as a result of my being a participant in the Activity, whether caused by the negligence of Hosts or otherwise.</p>
        <p>3. I further hereby agree to indemnify and save and hold harmless the Hosts and each of them, from any loss, liability, damage or costs they may incur due to my participation in the Activity, whether caused by the negligence of any or all of the Hosts, or otherwise.</p>
        <p>4. It is my express intent that this Release shall bind the members of my family and spouse, if I am alive, and my heirs, assigns and personal representative, if I am deceased, and shall be deemed as a Release, Waiver, Discharge and Covenant Not to Sue the above named Hosts.</p>
        <p><b>In signing this release, I acknowledge and represent that:</b></p>
        <p>A. I have read the foregoing release, understand it, and sign it voluntarily as my own free act and deed;</p>
        <p>B. No oral representation, statements or inducements, apart from the foregoing written agreement, have been made;</p>
        <p>C. I am at least eighteen (18) years of age and fully competent; and</p>
        <p>D. I execute this Release for full, adequate and complete consideration fully intending to be bound by same.</p>
        <p><b>I HAVE CAREFULLY READ THIS AGREEMENT AND FULLY UNDERSTAND ITS CONTENTS. I AM AWARE THAT THIS IS A RELEASE OF LIABILITY AND A CONTRACT BETWEEN MYSELF AND HOST(S) OF THIS ACTIVITY AND SIGN IT OF MY OWN FREE WILL.</b></p>
      </div>
      <form style="font-size: 12px;" method="POST" action="{% url 'waiver' %}">{% csrf_token %}
        {% for field in form %}
            <div class="form-group">
              <label for="{{ field.label }}">{{ field.label }}</label>
              {{ field }}
              {% if field.errors %}
                <p style="color: red; margin-top: 5px;">
                  <span class="glyphicon glyphicon-exclamation-sign" aria-hidden="true"></span>
                  <span class="sr-only">Error:</span>
                  {{ field.errors.0 }}
                </p>
              {% endif %}
            </div>
        {% endfor %}
        <p><b>By my signature, I acknowledge that I have read, understand, and agree to the policies above.</b></p>      
        <button style="width:100%;" type="submit" class="btn btn-success">I Agree</button>
      </form>
{% endblock %}

{% block extra_scripts %}
<script>
$('#id_phone').on('keypress', function(ev) {
    var keyCode = window.event ? ev.keyCode : ev.which;
    //codes for 0-9
    if (keyCode < 48 || keyCode > 57) {
        //codes for backspace, delete, enter
        if (keyCode != 0 && keyCode != 8 && keyCode != 13 && !ev.ctrlKey) {
            ev.preventDefault();
        }
    }
});

if ( $('[type="date"]').prop('type') != 'date' ) {
    $('#id_dob').datepicker({dateFormat: 'yy-mm-dd'});
};
</script>
{% endblock %}